const Homeproduct =
[
    {
        id: 1,
        Name: 'Apple',
        price: '251',
        image: 'image/image/image/apple.png',
        cat: 'fruit',
        type: 'new',
    },
    {
        id: 2,
        Name: 'Banana',
        price: '64',
        image: 'image/image/image/banana.png',
        cat: 'fruit',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Cherry',
        price: '120',
        image: 'image/image/image/cherry.png',
        cat: 'fruit',
        type: 'new',
    },
    {
        id: 4,
        Name: 'Guava',
        price: '44',
        image: 'image/image/image/guava.png',
        cat: 'fruit',
        type: 'new',
    },
    {
        id: 5,
        Name: 'Jackfruit',
        price: '98',
        image: 'image/image/image/jackfruit.png',
        cat: 'fruit',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'kiwi',
        price: '171',
        image: 'image/image/image/kiwi.png',
        cat: 'fruit',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'Mango',
        price: '120',
        image: 'image/image/image/mango.png',
        cat: 'fruit',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'Orange',
        price: '132',
        image: 'image/image/image/orange.png',
        cat: 'fruit',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'Pomegranate',
        price: '211',
        image: 'image/image/image/pomegranate.png',
        cat: 'fruit',
        type: 'top',
    },
    {
        id: 10,
        Name: 'Strawberry',
        price: '90',
        image: 'image/image/image/strawberry.png',
        cat: 'fruit',
        type: 'top',
    },
    {
        id: 11,
        Name: 'WaterMelon',
        price: '60',
        image: 'image/image/image/Watermelon.png',
        cat: 'fruit',
        type: 'top',
    },
    {
        id: 12,
        Name: 'Grapes',
        price: '56',
        image: 'image/image/image/grapes.png',
        cat: 'fruit',
        type: 'top',
    },
    {
        id: 13,
        Name: 'Beetroot',
        price: '807',
        image: 'image/image/image/beetroot.png',
        cat: 'vegetable',
        type: 'top',
    },
    {
        id: 14,
        Name: 'Brinjal',
        price: '807',
        image: 'image/image/image/Brinjal.png',
        cat: 'vegetable',
        type: 'top',
    },
    {
        id: 15,
        Name: 'Cabbage',
        price: '807',
        image: 'image/image/image/cabbage.png',
        cat: 'vegetable',
        type: 'top',
    },
    {
        id: 16,
        Name: 'Carrot',
        price: '807',
        image: 'image/image/image/carrot.png',
        cat: 'vegetable',
        type: 'top',
    },
    {
        id: 17,
        Name: 'Cauliflower',
        price: '807',
        image: 'image/image/image/cauliflower.png',
        cat: 'vegetable',
        type: 'top',
    },
    {
        id: 18,
        Name: 'Cucumber',
        price: '807',
        image: 'image/image/image/cucumber.png',
        cat: 'vegetable',
        type: 'top',
    },
    {
        id: 19,
        Name: 'Ladysfinger',
        price: '807',
        image: 'image/image/image/ladysfinger.png',
        cat: 'vegetable',
        type: 'top',
    },
    {
        id: 20,
        Name: 'Potato',
        price: '807',
        image: 'image/image/image/potato.png',
        cat: 'vegetable',
        type: 'top',
    },
    {
        id: 21,
        Name: 'Onion',
        price: '807',
        image: 'image/image/image/onion.png',
        cat: 'vegetable',
        type: 'top',
    },
    {
        id: 22,
        Name: ' Tomato',
        price: '807',
        image: 'image/image/image/tomato.png',
        cat: 'vegetable',
        type: 'top',
    },
    
]
export default Homeproduct